# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - release/PetclinicFront/v*
  paths:
    include:
    - /PetclinicFront/ 

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'PetclinicFront/PetclinicFront.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
  ##Datos adicionales 
  repository: 'petclinicfront-$(username)'
  dockerfile: 'PetclinicFront/Dockerfile'

steps:
# 1 - Build image
- task: Docker@2
  inputs:
    containerRegistry: 'acr-conexion'
    repository: '$(repository)'
    command: 'build'
    Dockerfile: '$(dockerfile)'
    


# 2 - Push image
- task: Docker@2
  inputs:
    containerRegistry: 'acr-conexion'
    repository: '$(repository)'
    command: 'push'



# 5 - Pusblish artifact

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: PetclinicFront/manifests
    artifact: 'deploy-to-aks'
    publishLocation: 'pipeline'

