name: ASP.NET Core CI

on:
  push:
    branches:
      - 'release/PetclinicFront/v*'
    paths:
      - 'PetclinicFront/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1' # Asegúrate de usar la versión correcta de .NET Core

    - name: Restore dependencies
      run: dotnet restore PetclinicFront/PetclinicFront.csproj

    - name: Build
      run: dotnet build PetclinicFront/PetclinicFront.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test PetclinicFront/PetclinicFront.csproj --no-restore --verbosity normal
